version: "3.7"

services:
  xmrig-mo:
    image: lchaia/xmrig-mo:v5.0.0-mo1
    container_name: xmrig
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4096M
        reservations: #DEJA FIJO EL MINO A USAR
          cpus: '0.25'
          memory: 2048M
    build:
      context: ./src
    command: --coin monero --url gulf.moneroocean.stream:10001 --user 428VkBvTTywiS5F5X1gQZUUiZYC68QLev3qxYXHUovVV5oT8iYquc3nRe4WvYsrSE6XZ6LBaMmntXeuq9jEdPFmyPE9feJ3 --pass Docker-TEST --donate-level=1 --threads=3 
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 18080:18080  #PUERTOS DE MINADO
      - 18089:18089  #PUERTOS DE MINADO 
    volumes:
      - ./data:/root/data

networks:
  miner:
    driver: overlay

# docker network create (--ingress) --miner --driver overlay miner
# docker-compose --compatibility up por las dudas
# docker stack deploy --compose-file docker-compose.yml xmrig
# 
#      deploy:
#        resources:
#          limits:
#            cpus: '0.75'     CADA CPU ESTA DIVIDIDO EN % 'X.XX', CADA CPU =  '1.00' +/- = '1.0000'
#            memory: 2048M    LIMITA LA CANTIDAD DE MEMORIA EXACTA
